name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      CONTAINER_REGISTRY_UN: ${{ secrets.AZURE_CONTAINER_REGISTRY_UN }}
      CONTAINER_REGISTRY_PW: ${{ secrets.AZURE_CONTAINER_REGISTRY_PW }}

    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Build and push the image
        run: |
          docker login --username pushkar14 --password ${{secrets.ARITHMETIC_SERVICE_GIT_TOKEN}} ghcr.io
          docker build -t ghcr.io/pushkar14-mst/arithmetic-service:$VERSION --file Dockerfile .  
          docker push ghcr.io/pushkar14-mst/arithmetic-service:$VERSION
      - name: Publish the image to azure container registry
        run: |
          echo "$CONTAINER_REGISTRY_PW" | docker login --username $CONTAINER_REGISTRY_UN --password-stdin $CONTAINER_REGISTRY
          docker tag ghcr.io/pushkar14-mst/arithmetic-service:$VERSION $CONTAINER_REGISTRY/arithmetic-service:$VERSION
          docker push $CONTAINER_REGISTRY/arithmetic-service:$VERSION
      - uses: tale/kubectl-action@v1.0.0
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.29.2
      - name: Deploy to kubernetes
        run: ./deploy.sh
