name: Docker Image CI for GHCR

on: push

permissions: write-all
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username pushkar14-mst --password ${{secrets.GITHUB_TOKEN}} ghcr.io
          docker build -t ghcr.io/pushkar14-mst/arithmetic-service:latest --file Dockerfile .  
          docker push ghcr.io/pushkar14-mst/arithmetic-service:latest
          docker pull ghcr.io/pushkar14-mst/arithmetic-service:latest
          docker run -p 8080:8080 ghcr.io/pushkar14-mst/arithmetic-service:latest
